import React from "react";
import type { Metadata } from "next";
import "./globals.css";

import { Inter, Playwrite_AU_NSW } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const playwrite = Playwrite_AU_NSW({
  display: "swap",
  variable: "--font-playwrite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR" className={`${inter.variable} ${playwrite.variable}`}>
      <body>{children}</body>
    </html>
  );
}
